import pandas as pd, numpy as np, json, re, collections
D="/home/user/Claude-/challenges/uk_legislation_reconstruction/dataset/public/"
c=pd.read_csv(D+"corpus.csv",keep_default_na=False)
tr=pd.read_csv(D+"train.csv",keep_default_na=False)
te=pd.read_csv(D+"test.csv",keep_default_na=False)
tt=pd.read_csv(D+"train_targets.csv",keep_default_na=False)
ss=pd.read_csv(D+"sample_submission.csv",keep_default_na=False)
print("corpus",c.shape,"train",tr.shape,"test",te.shape,"tt",tt.shape,"ss",ss.shape)
print("unique unit_id",c.unit_id.nunique(),"dup?",c.unit_id.duplicated().sum())
print("docs by (title,citation)",c.groupby(['document_title','citation']).ngroups, "by citation",c.citation.nunique())
print("\ndoc_date range",c.document_date.min(),c.document_date.max())
print("\nlabel kinds:")
def lk(l):
    m=re.match(r'^(s\.|Sch\.|art\.|reg\.|rule|para\.|Pt\.|r\.)',l)
    return m.group(1) if m else l.split()[0]
print(c.label.map(lk).value_counts().head(20))
print("\ntext len percentiles", np.percentile(c.text.str.len(),[50,90,99,100]).round(0))
print("\ncitation type: SI vs Act")
print(c.citation.str.contains('S.I.',regex=False).value_counts())
print("\n== QUERIES ==")
print("train acts",tr.act_citation.nunique(),"test acts",te.act_citation.nunique())
print("overlap", set(tr.act_citation)&set(te.act_citation))
print("\ntrain queries per act:"); print(tr.act_citation.value_counts())
print("\ntest queries per act:"); print(te.act_citation.value_counts())
print("\nquery date range tr",tr.date.min(),tr.date.max()," te",te.date.min(),te.date.max())
print("\nsection_label kinds tr", tr.section_label.map(lk).value_counts().to_dict())
print("section_label kinds te", te.section_label.map(lk).value_counts().to_dict())
tt['ids']=tt.amending_ids.map(json.loads)
print("\nn amending ids per train query:"); print(tt.ids.map(len).value_counts().sort_index())
print("mean",tt.ids.map(len).mean())
allids=set(c.unit_id); flat=[i for L in tt.ids for i in L]
print("ids in corpus?", len(flat), sum(1 for i in flat if i in allids))
print("distinct gold ids", len(set(flat)))
m=tr.merge(tt,on='item_id')
print("text changed vs enacted:", (m.enacted_text!=m.text_at_date).mean())
print("len ratio at_date/enacted", (m.text_at_date.str.len()/m.enacted_text.str.len()).describe().round(3).to_dict())
